# Use the official WordPress image as the base image
FROM webdevops/php-apache-dev:7.4
# Install nano
RUN apt-get update && apt-get install nano -y
# Install xdebug
RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

