
services:
  database:
    mem_limit: 2048m
    image: mariadb:10.6.4-focal
    restart: unless-stopped
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE : 'root'
      MYSQL_USER : 'root'
      MYSQL_PASSWORD : 'root'

    volumes:
      - db-data:/var/lib/mysql
    networks:
      - pruebatecnica-network

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin  
    restart: unless-stopped
    ports:
      - 8082:80
    environment:
      PMA_HOST : database
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - pruebatecnica-network

  apache:
    image: webdevops/php-apache-dev:7.4
    build:
      dockerfile: ./dockerfile/dockerfile  
    volumes:
      - /var/www/projects/pruebatecnica:/var/www/html
      - ./apache.conf:/opt/docker/etc/httpd/conf.d/dan-todo.conf # So when you use localhost it opens this path
      - ./xdebug/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - '86:80'
      - '444:443'

    networks:
      - pruebatecnica-network

volumes:
  db-data:

networks:
  pruebatecnica-network:
    driver: bridge
